2015-09-15 02:19:26.511 [error] <0.649.0> gen_server ibot_nodes_srv_connector terminated with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 183
2015-09-15 02:19:26.511 [error] <0.649.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 183 in gen_server:terminate/7 line 804
2015-09-15 02:19:26.512 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.649.0> exit with reason bad record core_info in ibot_nodes_srv_connector:run_node/1 line 183 in context child_terminated
2015-09-15 02:20:29.735 [error] <0.756.0> gen_server ibot_nodes_srv_connector terminated with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 170
2015-09-15 02:20:29.736 [error] <0.756.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 170 in gen_server:terminate/7 line 804
2015-09-15 02:20:29.736 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.756.0> exit with reason bad record core_info in ibot_nodes_srv_connector:run_node/1 line 170 in context child_terminated
2015-09-15 02:20:33.785 [error] <0.757.0> gen_server ibot_nodes_srv_connector terminated with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 219
2015-09-15 02:20:33.785 [error] <0.757.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 219 in gen_server:terminate/7 line 804
2015-09-15 02:20:33.785 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.757.0> exit with reason bad record core_info in ibot_nodes_srv_connector:run_node/1 line 219 in context child_terminated
2015-09-15 02:25:32.223 [error] <0.649.0> gen_server ibot_nodes_srv_connector terminated with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 151
2015-09-15 02:25:32.223 [error] <0.649.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 151 in gen_server:terminate/7 line 804
2015-09-15 02:25:32.223 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.649.0> exit with reason bad record core_info in ibot_nodes_srv_connector:run_node/1 line 151 in context child_terminated
2015-09-15 02:29:43.510 [error] <0.649.0> gen_server ibot_nodes_srv_connector terminated with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 151
2015-09-15 02:29:43.510 [error] <0.649.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 151 in gen_server:terminate/7 line 804
2015-09-15 02:29:43.510 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.649.0> exit with reason bad record core_info in ibot_nodes_srv_connector:run_node/1 line 151 in context child_terminated
2015-09-15 02:33:20.384 [error] <0.649.0> gen_server ibot_nodes_srv_connector terminated with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 221
2015-09-15 02:33:20.384 [error] <0.649.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: bad record core_info in ibot_nodes_srv_connector:run_node/1 line 221 in gen_server:terminate/7 line 804
2015-09-15 02:33:20.385 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.649.0> exit with reason bad record core_info in ibot_nodes_srv_connector:run_node/1 line 221 in context child_terminated
