2015-08-06 02:28:25.815 [error] emulator Error in process <0.753.0> on node 'core@alex-N550JK' with exit value: {{nocatch,[{reason,{error,{invalid_object_member,109}}},{mfa,{ibot_webi_handler,websocket_info,3}},{stacktrace,[{jiffy,encode,2,[{file,"src/jiffy.erl"},{line,41}]},{ibot_webi_handler,websocket_info,3,[{file,"src/ibot_we... 


2015-08-06 02:28:25.817 [error] <0.541.0> Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.753.0> exit with reason: {{nocatch,[{reason,{error,{invalid_object_member,109}}},{mfa,{ibot_webi_handler,websocket_info,3}},{stacktrace,[{jiffy,encode,2,[{file,"src/jiffy.erl"},{line,41}]},{ibot_webi_handler,websocket_info,3,[{file,"src/ibot_webi_handler.erl"},{line,149}]},{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]},{msg,{<0.651.0>,{pubsub,wsuiclient},{send_data_to_ui,'BLA_BLA_BLA',{"message #0 for UI"}}}},{req,[{socket,#Port<0.941>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.753.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},48079}},{host,<<"localhost">>},{host_info,undefined},{port,10101},{path,<<"/websocket">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:10101">>},{<<"connection">>,<<"Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>},{<<"origin">>,<<"http://localhost:10101">>},{<<"sec-websocket-version">>,<<"13">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36">>},{<<"accept-encoding">>,<<"gzip, deflate, sdch">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>},{<<"sec-websocket-key">>,<<"CW5hgC1fxMh+R5UY8MKQ0g==">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate; client_max_window_bits">>}]},{p_headers,[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[<<"client_max_window_bits">>]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_compress,false},{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,done},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,undefined_state}]},[{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]}

2015-08-06 02:33:24.399 [error] emulator Error in process <0.753.0> on node 'core@alex-N550JK' with exit value: {[{reason,badarith},{mfa,{ibot_webi_handler,websocket_info,3}},{stacktrace,[{ibot_webi_handler,websocket_info,3,[{file,"src/ibot_webi_handler.erl"},{line,149}]},{cowboy_websocket,handler_call,7,[{file,"src/cowboy_we... 


2015-08-06 02:33:24.400 [error] <0.541.0> Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.753.0> exit with reason: {[{reason,badarith},{mfa,{ibot_webi_handler,websocket_info,3}},{stacktrace,[{ibot_webi_handler,websocket_info,3,[{file,"src/ibot_webi_handler.erl"},{line,149}]},{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]},{msg,{<0.651.0>,{pubsub,wsuiclient},{send_data_to_ui,'BLA_BLA_BLA',{"message #0 for UI"}}}},{req,[{socket,#Port<0.941>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.753.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},48137}},{host,<<"localhost">>},{host_info,undefined},{port,10101},{path,<<"/websocket">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:10101">>},{<<"connection">>,<<"Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>},{<<"origin">>,<<"http://localhost:10101">>},{<<"sec-websocket-version">>,<<"13">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36">>},{<<"accept-encoding">>,<<"gzip, deflate, sdch">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>},{<<"sec-websocket-key">>,<<"3OPbulz9Hm8fn9XPFslg2w==">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate; client_max_window_bits">>}]},{p_headers,[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[<<"client_max_window_bits">>]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_compress,false},{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,done},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,undefined_state}],[{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]}

2015-08-06 02:37:14.383 [error] emulator Error in process <0.754.0> on node 'core@alex-N550JK' with exit value: {{nocatch,[{reason,{error,{invalid_object_member,116}}},{mfa,{ibot_webi_handler,websocket_info,3}},{stacktrace,[{jiffy,encode,2,[{file,"src/jiffy.erl"},{line,41}]},{ibot_webi_handler,websocket_info,3,[{file,"src/ibot_we... 


2015-08-06 02:37:14.384 [error] <0.541.0> Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.754.0> exit with reason: {{nocatch,[{reason,{error,{invalid_object_member,116}}},{mfa,{ibot_webi_handler,websocket_info,3}},{stacktrace,[{jiffy,encode,2,[{file,"src/jiffy.erl"},{line,41}]},{ibot_webi_handler,websocket_info,3,[{file,"src/ibot_webi_handler.erl"},{line,149}]},{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]},{msg,{<0.651.0>,{pubsub,wsuiclient},{send_data_to_ui,'BLA_BLA_BLA',{"message #0 for UI"}}}},{req,[{socket,#Port<0.942>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.754.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},48183}},{host,<<"localhost">>},{host_info,undefined},{port,10101},{path,<<"/websocket">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:10101">>},{<<"connection">>,<<"Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>},{<<"origin">>,<<"http://localhost:10101">>},{<<"sec-websocket-version">>,<<"13">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36">>},{<<"accept-encoding">>,<<"gzip, deflate, sdch">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>},{<<"sec-websocket-key">>,<<"PR6MxLxOVMZmSUaiDZdfTA==">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate; client_max_window_bits">>}]},{p_headers,[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[<<"client_max_window_bits">>]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_compress,false},{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,done},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,undefined_state}]},[{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]}

2015-08-06 02:38:44.601 [error] emulator Error in process <0.756.0> on node 'core@alex-N550JK' with exit value: {{try_clause,ok},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]}


2015-08-06 02:38:44.602 [error] <0.542.0> Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.756.0> exit with reason: {{try_clause,ok},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,resume,6,[{file,"src/cowboy_protocol.erl"},{line,545}]}]}

2015-08-20 03:13:13.060 [error] <0.650.0> gen_server ibot_nodes_srv_connector terminated with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:call/2 line 182
2015-08-20 03:13:13.060 [error] <0.650.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:terminate/7 line 804
2015-08-20 03:13:13.061 [error] <0.760.0> gen_server test_py_monitor terminated with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}}
2015-08-20 03:13:13.062 [error] <0.760.0> CRASH REPORT Process test_py_monitor with 0 neighbours exited with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:terminate/7 line 804
2015-08-20 03:13:13.062 [error] <0.763.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}}
2015-08-20 03:13:13.062 [error] <0.763.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:terminate/7 line 804
2015-08-20 03:13:13.062 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.650.0> exit with reason {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in context child_terminated
2015-08-20 03:13:15.285 [error] <0.784.0> gen_server ibot_nodes_srv_connector terminated with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:call/2 line 182
2015-08-20 03:13:15.286 [error] <0.784.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:terminate/7 line 804
2015-08-20 03:13:15.287 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.784.0> exit with reason {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in context child_terminated
2015-08-25 01:40:30.294 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.649.0> exit with reason error in context child_terminated
2015-08-25 01:41:51.888 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.752.0> exit with reason error in context child_terminated
2015-08-25 01:51:55.845 [error] <0.757.0> gen_server ibot_nodes_srv_connector terminated with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:call/2 line 182
2015-08-25 01:51:55.845 [error] <0.757.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:51:55.845 [error] <0.779.0> gen_server test_py_monitor terminated with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}}
2015-08-25 01:51:55.846 [error] <0.779.0> CRASH REPORT Process test_py_monitor with 0 neighbours exited with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:51:55.846 [error] <0.782.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}}
2015-08-25 01:51:55.847 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.757.0> exit with reason {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in context child_terminated
2015-08-25 01:51:55.847 [error] <0.782.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:52:42.559 [error] <0.808.0> gen_server ibot_nodes_srv_connector terminated with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:call/2 line 182
2015-08-25 01:52:42.560 [error] <0.808.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:52:42.561 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.808.0> exit with reason {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in context child_terminated
2015-08-25 01:52:42.561 [error] <0.812.0> gen_server test_py_monitor terminated with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}}
2015-08-25 01:52:42.562 [error] <0.812.0> CRASH REPORT Process test_py_monitor with 0 neighbours exited with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:55:42.319 [error] <0.813.0> gen_server ibot_nodes_srv_connector terminated with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:call/2 line 182
2015-08-25 01:55:42.319 [error] <0.813.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:55:42.320 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.813.0> exit with reason {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in context child_terminated
2015-08-25 01:55:42.321 [error] <0.816.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}}
2015-08-25 01:55:42.321 [error] <0.816.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {{function_clause,[{gen,call,["BLA_BLA_BLA_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"BLA_BLA_BLA_monitor",...},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:56:08.099 [error] <0.832.0> gen_server ibot_nodes_srv_connector terminated with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:call/2 line 182
2015-08-25 01:56:08.099 [error] <0.832.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in gen_server:terminate/7 line 804
2015-08-25 01:56:08.099 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.832.0> exit with reason {{function_clause,[{gen,call,["test_py_monitor",'$gen_call',{stop},5000],[{file,"gen.erl"},{line,149}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,178}]},{ibot_nodes_srv_connector,handle_info,2,[{file,"src/ibot_nodes_srv_connector.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[{"test_py_monitor",'core@alex-N550JK'},...]}} in context child_terminated
2015-08-25 02:16:42.608 [error] <0.809.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: test
2015-08-25 02:16:42.609 [error] <0.806.0> gen_server test_py_monitor terminated with reason: test
2015-08-25 02:16:42.609 [error] <0.806.0> CRASH REPORT Process test_py_monitor with 0 neighbours exited with reason: test in gen_server:terminate/7 line 804
2015-08-25 02:16:42.609 [error] <0.809.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: test in gen_server:terminate/7 line 804
2015-08-25 02:16:42.609 [error] <0.647.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.649.0> exit with reason test in context child_terminated
2015-08-30 17:27:30.669 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.756.0> exit with reason normal in context child_terminated
2015-08-30 17:27:30.697 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.757.0> exit with reason normal in context child_terminated
2015-08-30 17:27:30.701 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.760.0> exit with reason normal in context child_terminated
2015-08-30 17:27:30.709 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.763.0> exit with reason normal in context child_terminated
2015-08-30 17:27:30.711 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.766.0> exit with reason normal in context child_terminated
2015-08-30 17:27:30.714 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.769.0> exit with reason normal in context child_terminated
2015-08-30 17:27:30.714 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.769.0> exit with reason reached_max_restart_intensity in context shutdown
2015-08-30 17:36:34.537 [error] <0.782.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: error
2015-08-30 17:36:34.538 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.650.0> exit with reason error in context child_terminated
2015-08-30 17:36:34.538 [error] <0.782.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: error in gen_server:terminate/7 line 804
2015-08-30 17:37:06.517 [error] <0.792.0> gen_server ibot_nodes_srv_connector terminated with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in gen_server:call/2 line 182
2015-08-30 17:37:06.517 [error] <0.792.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in gen_server:terminate/7 line 804
2015-08-30 17:37:06.517 [error] <0.798.0> gen_server test_py_monitor terminated with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop)
2015-08-30 17:37:06.518 [error] <0.798.0> CRASH REPORT Process test_py_monitor with 0 neighbours exited with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in gen_server:terminate/7 line 804
2015-08-30 17:37:06.518 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.792.0> exit with reason no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in context child_terminated
2015-08-30 17:37:40.870 [error] <0.800.0> gen_server ibot_nodes_srv_connector terminated with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in gen_server:call/2 line 182
2015-08-30 17:37:40.870 [error] <0.800.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in gen_server:terminate/7 line 804
2015-08-30 17:37:40.871 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.800.0> exit with reason no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in context child_terminated
2015-08-30 17:41:05.446 [error] <0.818.0> gen_server ibot_nodes_srv_connector terminated with reason: no such process or port in call to gen_server:call(test_py_monitor, stop) in gen_server:call/2 line 182
2015-08-30 17:41:05.447 [error] <0.818.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: no such process or port in call to gen_server:call(test_py_monitor, stop) in gen_server:terminate/7 line 804
2015-08-30 17:41:05.447 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.818.0> exit with reason no such process or port in call to gen_server:call(test_py_monitor, stop) in context child_terminated
2015-08-30 17:42:27.984 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.836.0> exit with reason error in context child_terminated
2015-08-30 17:42:27.984 [error] <0.872.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: error
2015-08-30 17:42:27.984 [error] <0.868.0> gen_server test_py_monitor terminated with reason: error
2015-08-30 17:42:27.984 [error] <0.872.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: error in gen_server:terminate/7 line 804
2015-08-30 17:42:27.984 [error] <0.868.0> CRASH REPORT Process test_py_monitor with 0 neighbours exited with reason: error in gen_server:terminate/7 line 804
2015-08-30 17:42:33.095 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.873.0> exit with reason error in context child_terminated
2015-08-30 17:42:43.987 [error] <0.885.0> gen_server ibot_nodes_srv_connector terminated with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in gen_server:call/2 line 182
2015-08-30 17:42:43.988 [error] <0.885.0> CRASH REPORT Process ibot_nodes_srv_connector with 0 neighbours exited with reason: no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in gen_server:terminate/7 line 804
2015-08-30 17:42:43.988 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.885.0> exit with reason no such process or port in call to gen_server:call('BLA_BLA_BLA_monitor', stop) in context child_terminated
2015-08-30 17:44:05.128 [error] <0.892.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: error
2015-08-30 17:44:05.129 [error] <0.892.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: error in gen_server:terminate/7 line 804
2015-08-30 17:44:05.129 [error] <0.648.0> Supervisor ibot_nodes_sup had child ibot_nodes_srv_connector started with ibot_nodes_srv_connector:start_link() at <0.888.0> exit with reason error in context child_terminated
2015-08-30 17:56:00.739 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.761.0> exit with reason normal in context child_terminated
2015-08-30 17:56:28.076 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.776.0> exit with reason normal in context child_terminated
2015-08-30 17:56:28.081 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.788.0> exit with reason normal in context child_terminated
2015-08-30 17:56:28.083 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.791.0> exit with reason normal in context child_terminated
2015-08-30 17:56:28.085 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.794.0> exit with reason normal in context child_terminated
2015-08-30 17:56:28.103 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.797.0> exit with reason normal in context child_terminated
2015-08-30 17:56:28.111 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.800.0> exit with reason normal in context child_terminated
2015-08-30 17:56:28.112 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.800.0> exit with reason reached_max_restart_intensity in context shutdown
2015-08-30 17:58:54.193 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.757.0> exit with reason normal in context child_terminated
2015-08-31 00:14:26.280 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.764.0> exit with reason normal in context child_terminated
2015-08-31 00:14:26.284 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.766.0> exit with reason normal in context child_terminated
2015-08-31 00:14:26.285 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.769.0> exit with reason normal in context child_terminated
2015-08-31 00:14:26.290 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.772.0> exit with reason normal in context child_terminated
2015-08-31 00:14:26.294 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.775.0> exit with reason normal in context child_terminated
2015-08-31 00:14:26.297 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.778.0> exit with reason normal in context child_terminated
2015-08-31 00:14:26.297 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.778.0> exit with reason reached_max_restart_intensity in context shutdown
2015-08-31 00:21:01.833 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.756.0> exit with reason normal in context child_terminated
2015-08-31 00:21:01.838 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.757.0> exit with reason normal in context child_terminated
2015-08-31 00:21:01.839 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.760.0> exit with reason normal in context child_terminated
2015-08-31 00:21:01.848 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.763.0> exit with reason normal in context child_terminated
2015-08-31 00:21:01.855 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.766.0> exit with reason normal in context child_terminated
2015-08-31 00:21:01.857 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.769.0> exit with reason normal in context child_terminated
2015-08-31 00:21:01.857 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.769.0> exit with reason reached_max_restart_intensity in context shutdown
2015-08-31 00:46:04.446 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.757.0> exit with reason normal in context child_terminated
2015-08-31 00:47:09.002 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.760.0> exit with reason normal in context child_terminated
2015-08-31 00:47:38.329 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.763.0> exit with reason normal in context child_terminated
2015-08-31 00:47:38.332 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.764.0> exit with reason normal in context child_terminated
2015-08-31 00:47:38.334 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.767.0> exit with reason normal in context child_terminated
2015-08-31 00:47:38.342 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.770.0> exit with reason normal in context child_terminated
2015-08-31 00:47:38.345 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.773.0> exit with reason normal in context child_terminated
2015-08-31 00:47:38.348 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.776.0> exit with reason normal in context child_terminated
2015-08-31 00:47:38.348 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.776.0> exit with reason reached_max_restart_intensity in context shutdown
2015-08-31 01:05:45.482 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.757.0> exit with reason normal in context child_terminated
2015-08-31 01:05:50.801 [error] <0.759.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:call/2 line 182
2015-08-31 01:05:50.801 [error] <0.759.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:terminate/7 line 804
2015-08-31 01:05:50.802 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.759.0> exit with reason {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in context shutdown_error
2015-08-31 01:06:11.135 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.762.0> exit with reason normal in context child_terminated
2015-08-31 01:06:16.453 [error] <0.764.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:call/2 line 182
2015-08-31 01:06:16.454 [error] <0.764.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:terminate/7 line 804
2015-08-31 01:06:16.454 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.764.0> exit with reason {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in context shutdown_error
2015-08-31 01:11:14.504 [error] <0.782.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:call/2 line 182
2015-08-31 01:11:14.504 [error] <0.782.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:terminate/7 line 804
2015-08-31 01:11:14.505 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.782.0> exit with reason {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in context shutdown_error
2015-08-31 01:12:04.426 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.821.0> exit with reason killed in context shutdown_error
2015-08-31 01:17:00.620 [error] <0.762.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:call/2 line 182
2015-08-31 01:17:00.620 [error] <0.762.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:terminate/7 line 804
2015-08-31 01:17:00.620 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.762.0> exit with reason {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in context shutdown_error
2015-08-31 01:26:46.229 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.762.0> exit with reason killed in context shutdown_error
2015-08-31 01:27:47.441 [error] <0.765.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:call/2 line 182
2015-08-31 01:27:47.441 [error] <0.765.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:terminate/7 line 804
2015-08-31 01:27:47.441 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.765.0> exit with reason {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in context shutdown_error
2015-08-31 01:45:13.470 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.772.0> exit with reason killed in context shutdown_error
2015-08-31 01:47:56.324 [error] <0.756.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:call/2 line 182
2015-08-31 01:47:56.324 [error] <0.756.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in gen_server:terminate/7 line 804
2015-08-31 01:47:56.324 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.756.0> exit with reason {timeout,{gen_server,call,[ibot_nodes_srv_connector,{restart_node,'BLA_BLA_BLA'}]}} in context shutdown_error
2015-08-31 01:51:38.114 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.760.0> exit with reason normal in context child_terminated
2015-08-31 01:51:38.114 [error] <0.647.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.761.0> exit with reason normal in context shutdown_error
2015-08-31 01:54:31.088 [error] <0.757.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: bad return value: {stop,normal,shutdown_ok,{state,"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}}
2015-08-31 01:54:31.088 [error] <0.757.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: bad return value: {stop,normal,shutdown_ok,{state,"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}} in gen_server:terminate/7 line 804
2015-08-31 01:54:31.089 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.757.0> exit with reason bad return value: {stop,normal,shutdown_ok,{state,"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}} in context child_terminated
2015-08-31 01:54:31.092 [error] <0.758.0> gen_server 'BLA_BLA_BLA_monitor' terminated with reason: bad return value: {stop,normal,shutdown_ok,{state,"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}}
2015-08-31 01:54:31.092 [error] <0.758.0> CRASH REPORT Process 'BLA_BLA_BLA_monitor' with 0 neighbours exited with reason: bad return value: {stop,normal,shutdown_ok,{state,"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}} in gen_server:terminate/7 line 804
2015-08-31 01:54:31.093 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.758.0> exit with reason bad return value: {stop,normal,shutdown_ok,{state,"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}} in context shutdown_error
2015-08-31 01:57:42.280 [error] <0.648.0> Supervisor ibot_nodes_sup had child 'BLA_BLA_BLA_monitor' started with ibot_nodes_srv_monitor:start_link({"BLA_BLA_BLA",'BLA_BLA_BLA','alex-N550JK','BLA_BLA_BLA@alex-N550JK'}) at <0.757.0> exit with reason killed in context shutdown_error
2015-08-31 23:09:18.622 [error] emulator Error in process <0.754.0> on node 'core@alex-N550JK' with exit value: {[{reason,undef},{mfa,{ibot_webi_handler,websocket_handle,3}},{stacktrace,[{ibot_core_cmd,run_exec,['javac -classpath "/usr/lib/erlang/lib/jinterface-1.5.12/priv/OtpErlang.jar:/home/alex/iBotOS/iBotOS/JLib/lib/Node.jar" /home/alex/ErlangTest/test_project/dev/msg/java/*.java'... 


2015-08-31 23:09:18.624 [error] <0.541.0> Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.754.0> exit with reason: {[{reason,undef},{mfa,{ibot_webi_handler,websocket_handle,3}},{stacktrace,[{ibot_core_cmd,run_exec,['javac -classpath "/usr/lib/erlang/lib/jinterface-1.5.12/priv/OtpErlang.jar:/home/alex/iBotOS/iBotOS/JLib/lib/Node.jar" /home/alex/ErlangTest/test_project/dev/msg/java/*.java'],[]},{ibot_generator_msg_srv,generate_msg_source_files,2,[{file,"src/ibot_generator_msg_srv.erl"},{line,97}]},{ibot_generator_msg_srv,generate_msg_source_files,2,[{file,"src/ibot_generator_msg_srv.erl"},{line,93}]},{ibot_generator_msg_srv,generate_msg_srv,1,[{file,"src/ibot_generator_msg_srv.erl"},{line,32}]},{ibot_generator_msg_srv,generate_all_msg_srv,0,[{file,"src/ibot_generator_msg_srv.erl"},{line,61}]},{ibot_webi_handler,websocket_handle,3,[{file,"src/ibot_webi_handler.erl"},{line,87}]},{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]},{msg,{text,<<"{\"generateAllMsgs\" : \"\"}">>}},{req,[{socket,#Port<0.948>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.754.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},60097}},{host,<<"localhost">>},{host_info,undefined},{port,10101},{path,<<"/websocket">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:10101">>},{<<"connection">>,<<"Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>},{<<"origin">>,<<"http://localhost:10101">>},{<<"sec-websocket-version">>,<<"13">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36">>},{<<"accept-encoding">>,<<"gzip, deflate, sdch">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>},{<<"sec-websocket-key">>,<<"5+DPgw+mEQJptxQOV5xQjA==">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate; client_max_window_bits">>}]},{p_headers,[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[<<"client_max_window_bits">>]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_compress,false},{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,done},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,undefined_state}],[{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}

2015-08-31 23:11:28.862 [error] emulator Error in process <0.694.0> on node 'core@alex-N550JK' with exit value: {[{reason,undef},{mfa,{ibot_webi_handler,websocket_handle,3}},{stacktrace,[{ibot_core_cmd,run_exec,['javac -classpath "/usr/lib/erlang/lib/jinterface-1.5.12/priv/OtpErlang.jar:/home/alex/iBotOS/iBotOS/JLib/lib/Node.jar" /home/alex/ErlangTest/test_project/dev/msg/java/*.java'... 


2015-08-31 23:11:28.864 [error] <0.542.0> Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.694.0> exit with reason: {[{reason,undef},{mfa,{ibot_webi_handler,websocket_handle,3}},{stacktrace,[{ibot_core_cmd,run_exec,['javac -classpath "/usr/lib/erlang/lib/jinterface-1.5.12/priv/OtpErlang.jar:/home/alex/iBotOS/iBotOS/JLib/lib/Node.jar" /home/alex/ErlangTest/test_project/dev/msg/java/*.java'],[]},{ibot_generator_msg_srv,generate_msg_source_files,2,[{file,"src/ibot_generator_msg_srv.erl"},{line,97}]},{ibot_generator_msg_srv,generate_msg_source_files,2,[{file,"src/ibot_generator_msg_srv.erl"},{line,93}]},{ibot_generator_msg_srv,generate_msg_srv,1,[{file,"src/ibot_generator_msg_srv.erl"},{line,32}]},{ibot_generator_msg_srv,generate_all_msg_srv,0,[{file,"src/ibot_generator_msg_srv.erl"},{line,61}]},{ibot_webi_handler,websocket_handle,3,[{file,"src/ibot_webi_handler.erl"},{line,87}]},{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]},{msg,{text,<<"{\"generateAllMsgs\" : \"\"}">>}},{req,[{socket,#Port<0.915>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.694.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},60106}},{host,<<"localhost">>},{host_info,undefined},{port,10101},{path,<<"/websocket">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:10101">>},{<<"connection">>,<<"Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>},{<<"origin">>,<<"http://localhost:10101">>},{<<"sec-websocket-version">>,<<"13">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36">>},{<<"accept-encoding">>,<<"gzip, deflate, sdch">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>},{<<"sec-websocket-key">>,<<"uyXQ2FTCk3A/tboFGYO07w==">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate; client_max_window_bits">>}]},{p_headers,[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[<<"client_max_window_bits">>]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_compress,false},{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,done},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,undefined_state}],[{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}

